<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>name</key>
	<string>Ansible</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.ansible</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.ansible</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)((#).*)</string>
			<key>name</key>
			<string>comment.line.number-sign.ansible</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\{\{ *[^\{\}]+ *\}\})|(\$\{[^\{\}]+\})</string>
			<key>name</key>
			<string>storage.type.ansible</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.ansible</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\- (name\:|include\:) (.*)|(^(- |\s*)\w+\:)</string>
			<key>name</key>
			<string>keyword.other.ansible</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\w+)(=)\"?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.ansible</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>text</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.other.ansible</string>
			<key>end</key>
			<string>\"?\s</string>
			<key>name</key>
			<string>variable.complex.ansible</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>constant.other.ansible</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ansible</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\[[0-9a-zA-Z_-]+(((\:)children)*)\])</string>
			<key>name</key>
			<string>string.quoted.double.ansible</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ansible</string>
	<key>uuid</key>
	<string>787ae642-b4ae-48b1-94e9-f935bec43a8f</string>
</dict>
</plist>
